apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: luex0pjqc-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: luex0pjqc-nodejs 
  name: luex0pjqc-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: luex0pjqc-nodejs 
